name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol libsqlite3-dev
    - name: Library
      run: |
        set COB_LIBRARY_PATH = /.
        set PATH=$PATH:/.
    - name: Initialize database from .tests/SQL.txt
      run: |
        sqlite3 test.db < ./tests/SQL.txt        
    - name: sqlite_callback
      run: cobc -m -fdebugging-line sqlite_callback.cob -lsqlite3
    - name: sum
      run: cobc -m -fdebugging-line sum.cob -lsqlite3
    - name: Ls
      run: ls
    - name: test_sum
      run: cobc -o test_sum test_sum.cob -lsqlite3
    - name: Ls
      run: ls
    - name: PATH
      run: echo $PATH
    - name: path
      run: echo $PATH
    - name: Env
      run: cobcrun --runtime-config
    - name: Compiler info
      run: cobc --info
    - name: Run tests
      run: |
        test_sum
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
