name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol libsqlite3-dev
    - name: Initialize database from .tests/SQL.txt
      run: |
        sqlite3 test.db < ./tests/SQL.txt
    - name: Compile COBOL code
      run: |
        cobc -c -lsqlit3 sqlite3.c
    - name: Compile COBOL code
      run: | 
        cobc -x -free -o sum sum.cob
        cobc -x -lsqlite3 test_sum.cob sqlite3.o
    - name: Run tests
      run: |
        cobcrun test_sum
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
