name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COB_LIBRARY_PATH: /home/runner/work/workflow-cobol/workflow-cobol
  COB_FILE_PATH: /home/runner/work/workflow-cobol/workflow-cobol

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol libsqlite3-dev
    - name: Get amalgamation source code SQLITE
      run: |
        wget https://www.sqlite.org/snapshot/sqlite-snapshot-202301041518.tar.gz
        mkdir sqlite_folder
        tar -xvf sqlite-snapshot-202301041518.tar.gz -C sqlite_folder --strip-components 1
        cp ./sqlite_folder/sqlite3.c ./sqlite3.c
    - name: Initialize database from .tests/SQL.txt
      run: |
        sqlite3 test.db < ./tests/SQL.txt        
    - name: Compile the C code SQLITE
      run: |
        cobc -c -lsqlit3 sqlite3.c
    - name: compil - SUM
      run: cobc -m -fdebugging-line MAIN.cob -lsqlite3
    - name: compil - TEST-SUM
      run: |
        cobc -x -o test_sum TEST-SUM.cob sqlite3.o MAIN.so -lsqlite3
    - name: Ls
      run: ls
    - name: Env
      run: cobcrun --runtime-config
    - name: Compiler info
      run: cobc --info
    - name: Run tests
      run: |
        ./test_sum
        echo $?
        if [[ $? -ne 21 ]]; then
          echo "Tests Succeed"
          exit 0
        else
          echo "Tests Failed"
          exit 1
        fi
