name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol libsqlite3-dev
    - name: Initialize database from .tests/SQL.txt
      run: |
        sqlite3 test.db < ./tests/SQL.txt
    - name: Compile COBOL code
      run: | 
        cobc -m -fdebugging-line sqlite_callback.cob -lsqlite3
        cobc -m -fdebugging-line sum.cob -lsqlite3
        cobc -x -fdebugging-line test_sum.cob -lsqlite3
    - name: Ls
      run: ls
    - name: Library
      run: |
        export COB_LIBRARY_PATH=.
    - name: Run tests
      run: |
        cobcrun test_sum
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
