name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol
    - name: Install DB2
      run: |
        wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ibm_db2-1.9.6.1.tar
        tar -xvf db2exc.tar.gz
        ./db2/install/db2_install -b db2
        rm db2exc.tar.gz
    - name: Create DB2 user
      run: |
        db2 create user user using password
    - name: Initialize DB2 database
      run: |
        db2start
        db2 -tvf ./tests/SQL.txt
    - name: Compile COBOL test_sum
      run: cobc -x -free -o test_sum .tests/test_sum.cob
    - name: Compile COBOL sum
      run: cobc -x -free -o sum sum.cob
    - name: Run tests
      run: |
        cobcrun test_sum
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
    - name: Push code to GitHub
      if: success()
      run: git push