name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COB_LIBRARY_PATH: /home/runner/work/workflow-cobol/workflow-cobol
  COB_FILE_PATH: /home/runner/work/workflow-cobol/workflow-cobol

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol libsqlite3-dev
    - name: A
      run: |
        wget https://www.sqlite.org/snapshot/sqlite-snapshot-202301041518.tar.gz
        tar -xvf sqlite-snapshot-202301041518.tar.gz
        ls sqlite-snapshot-202301041518
        .sqlite-snapshot-202301041518/sqlite3.c > ${COB_FILE_PATH}/sqlite3.c
    - name: Initialize database from .tests/SQL.txt
      run: |
        sqlite3 test.db < ./tests/SQL.txt        
    - name: Compile the C code SQLITE
      run: |
        cobc -c -lsqlit3 sqlite3.c
    - name: sqlite_callback
      run: cobc -m -fdebugging-line sqlite_callback.cob -lsqlite3
    - name: sum
      run: cobc -m -fdebugging-line sum.cob -lsqlite3
    - name: test_sum
      run: |
        cobc -x -o test_sum test_sum.cob -lsqlite3
    - name: Ls
      run: ls
    - name: Env
      run: cobcrun --runtime-config
    - name: Compiler info
      run: cobc --info
    - name: Run tests
      run: |
        ./test_sum
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
